package sampling.impl;

import primitives.Point;
import sampling.api.Beam;
import primitives.Ray;
import primitives.Vector;
import sampling.api.Sampler;

import java.util.List;

import static primitives.Util.isZero;

/**
 * A class for generating a beam of rays in a 3D scene.
 * The beam is generated by creating points using a sampler and mapping them to 3D space.
 *
 * @author David &amp; Yehuda
 */
public class BeamGenerator {

    /**
     * Creates a new beam generator instance.
     */
    public BeamGenerator() {
    }

    /**
     * The sampler used to generate points for the beam.
     */
    private Sampler sampler = new JitteredSampler();

    /**
     * Sets the sampler to use for beam generation.
     *
     * @param sampler the sampler strategy to use
     * @return this BeamGenerator instance for method chaining
     */
    public BeamGenerator setSampler(Sampler sampler) {
        this.sampler = sampler;
        return this;
    }

    /**
     * Generates a beam of rays based on a center ray, size, distance, and sampler.
     *
     * @param centerRay The central ray from which the beam is generated
     * @param size      The diameter of the circular area for the beam
     * @param distance  The distance from the center ray's origin to the target plane
     * @param amount    The number of rays to generate in the beam
     * @return A Beam object containing the generated rays
     */
    public Beam generateBeam(Ray centerRay, double size, double distance, int amount) {
        // If only 1 ray is requested or size is 0, return just the center ray
        if (amount <= 1 || isZero(size)) {
            return new Beam(List.of(centerRay));
        }

        Vector vTo = centerRay.direction();

        // Choose a helper vector to build the local 3D coordinate system
        Vector tempVector = Math.abs(vTo.dotProduct(Vector.AXIS_Z)) > 0.9
                ? Vector.AXIS_Y
                : Vector.AXIS_Z;

        // Create local orthonormal basis (X and Y axes)
        Vector vRight = vTo.crossProduct(tempVector).normalize();
        Vector vUp = vRight.crossProduct(vTo); // Already normalized

        Point origin = centerRay.origin();
        Vector baseVector = vTo.scale(distance);

        // Map 2D sample points directly to 3D rays
        List<Ray> rays = sampler.generatePoints(amount, size).stream()
                .map(p2d -> {
                    Vector dir = baseVector;
                    if (!isZero(p2d.x())) {
                        dir = dir.add(vRight.scale(p2d.x()));
                    }
                    if (!isZero(p2d.y())) {
                        dir = dir.add(vUp.scale(p2d.y()));
                    }
                    return new Ray(origin, dir);
                })
                .toList();

        return new Beam(rays);
    }
}