package sampling.impl;

import primitives.Point;
import sampling.api.Beam;
import primitives.Ray;
import primitives.Vector;
import sampling.api.Point2D;
import sampling.api.Sampler;

import java.util.ArrayList;
import java.util.List;

import static primitives.Util.isZero;

/**
 * A class for generating a beam of rays in a 3D scene.
 * The beam is generated by creating points using a sampler and mapping them to 3D space.
 *
 * @author David &amp; Yehuda
 */
public class BeamGenerator {

    /**
     * Creates a new beam generator instance.
     */
    public BeamGenerator() {
    }

    /**
     * The sampler used to generate points for the beam.
     */
    private Sampler sampler = new JitteredSampler();

    /**
     * Sets the sampler to use for beam generation.
     *
     * @param sampler the sampler strategy to use
     * @return this BeamGenerator instance for method chaining
     */
    public BeamGenerator setSampler(Sampler sampler) {
        this.sampler = sampler;
        return this;
    }



    /**
     * Generates a beam of rays based on a center ray, size, distance, and sampler.
     *
     * @param centerRay The central ray from which the beam is generated
     * @param size      The diameter of the circular area for the beam
     * @param distance  The distance from the center ray's origin to the target plane
     * @param amount    The number of rays to generate in the beam
     * @return A Beam object containing the generated rays
     */
    public Beam generateBeam(Ray centerRay, double size, double distance, int amount) {
        // If only 1 ray is requested or size is 0, return just the center ray
        if (amount <= 1 || isZero(size)) {
            return new Beam(List.of(centerRay));
        }

        Vector vTo = centerRay.direction();

        // Choose a helper vector to build the local 3D coordinate system.
        // If vTo is almost parallel to Z axis, use Y axis instead.
        Vector tempVector = Math.abs(vTo.dotProduct(Vector.AXIS_Z)) > 0.9
                ? Vector.AXIS_Y
                : Vector.AXIS_Z;

        // Create local X and Y axis vectors (Orthonormal Basis)
        Vector vRight = vTo.crossProduct(tempVector).normalize();
        Vector vUp = vRight.crossProduct(vTo); // Already normalized

        // Find the center point on the target plane
        Point pTarget = centerRay.origin().add(vTo.scale(distance));

        // Get 2D sample points from the current sampler
        List<Point2D> samples = sampler.generatePoints(amount, size);
        List<Ray> rays = new ArrayList<>(samples.size());

        // Convert each 2D sample point to a 3D ray
        for (Point2D p2d : samples) {
            Point p = pTarget;

            // Move point along local X axis
            if (!isZero(p2d.x())) {
                p = p.add(vRight.scale(p2d.x()));
            }

            // Move point along local Y axis
            if (!isZero(p2d.y())) {
                p = p.add(vUp.scale(p2d.y()));
            }

            // Create new ray from origin to the target point
            rays.add(new Ray(centerRay.origin(), p.subtract(centerRay.origin())));
        }

        return new Beam(rays);
    }
}