package sampling;

import primitives.Point;
import renderer.Beam;
import primitives.Ray;
import primitives.Vector;
import sampling.api.Point2D;
import sampling.api.Sampler;
import sampling.impl.JitteredSampler;

import java.util.ArrayList;
import java.util.List;

/**
 * A class for generating a beam of rays in a 3D scene.
 * The beam is generated by creating points using a sampler and mapping them to 3D space.
 *
 * @author David &amp; Yehuda
 */
public class BeamGenerator {

    /**
     * Creates a new beam generator instance.
     */
    public BeamGenerator() {
    }

    /**
     * The sampler used to generate points for the beam.
     */
    private Sampler sampler = new JitteredSampler();

    /**
     * Sets the sampler to use for beam generation.
     *
     * @param sampler the sampler strategy to use
     * @return this BeamGenerator instance for method chaining
     */
    public BeamGenerator setSampler(Sampler sampler) {
        this.sampler = sampler;
        return this;
    }



    /**
     * Generates a beam of rays based on a center ray, size, distance, and sampler.
     *
     * @param centerRay The central ray from which the beam is generated
     * @param size      The diameter of the circular area for the beam
     * @param distance  The distance from the center ray's origin to the target plane
     * @param amount    The number of rays to generate in the beam
     * @return A Beam object containing the generated rays
     */
    public Beam generateBeam(Ray centerRay, double size, double distance, int amount) {

        if (amount <= 1) {
            return new Beam(List.of(centerRay));
        }

        Vector vTo = centerRay.direction();

        double dotProd = vTo.dotProduct(Vector.AXIS_Z);

        Vector tempVector;
        if (Math.abs(dotProd) > 0.9) {
            tempVector = Vector.AXIS_Y;
        } else {
            tempVector = Vector.AXIS_Z;
        }

        Vector vRight = vTo.crossProduct(tempVector).normalize();
        Vector vUp = vRight.crossProduct(vTo).normalize();

        List<Point2D> samples = sampler.generatePoints(amount, size);
        List<Ray> rays = new ArrayList<>();

        Point pTarget = centerRay.origin().add(vTo.scale(distance));

        for (Point2D p2d : samples) {
            Point p = pTarget;

            if (p2d.getX() != 0) {
                p = p.add(vRight.scale(p2d.getX()));
            }
            if (p2d.getY() != 0) {
                p = p.add(vUp.scale(p2d.getY()));
            }

            rays.add(new Ray(centerRay.origin(), p.subtract(centerRay.origin())));
        }

        return new Beam(rays);
    }
}