package renderer;

import primitives.Point;
import primitives.Point2D;
import primitives.Ray;
import primitives.Vector;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * A class for generating a beam of rays in a 3D scene. The beam is generated by creating a grid of points in a circular area and mapping them to 3D space based on the direction of the center ray.
 * The class supports jittering to avoid unnatural patterns in the generated rays.
 *
 * @author David &amp; Yehuda
 */

public class BeamGenerator {

    /**
     * Random number generator for jittering
     */
    private static final Random RANDOM = new Random();

    /**
     * Flag to determine whether to use jittering or not
     */
    private boolean useJitter = true;

    /**
     * Sets whether to use jittering when generating the grid of points.
     *
     * @param useJitter true to enable jittering, false to disable
     * @return This BeamGenerator instance for method chaining
     */
    public BeamGenerator setUseJitter(boolean useJitter) {
        this.useJitter = useJitter;
        return this;
    }

    /**
     * Generates a circular grid of 2D points with Jittering.
     *
     * @param amount The base number of points along one side (before circular compensation)
     * @param size   The diameter of the circular target area
     * @return A list of Point2D objects inside the circle
     */
    public List<Point2D> generateGrid(int amount, double size) {
        List<Point2D> points = new ArrayList<>();

        if (amount <= 1) {
            points.add(new Point2D(0, 0));
            return points;
        }

        int effectiveAmount = (int) Math.ceil(amount * Math.sqrt(4 / Math.PI));

        double step = size / (effectiveAmount - 1);
        double start = -size / 2;
        double radius = size / 2;
        double radiusSq = radius * radius;

        for (int i = 0; i < effectiveAmount; i++) {
            for (int j = 0; j < effectiveAmount; j++) {
                double x = start + i * step;
                double y = start + j * step;

                if (useJitter) {
                    x += (RANDOM.nextDouble() - 0.5) * step;
                    y += (RANDOM.nextDouble() - 0.5) * step;
                }

                if (x * x + y * y <= radiusSq) {
                    points.add(new Point2D(x, y));
                }
            }
        }

        return points;
    }

    /**
     * Generates a beam of rays based on a center ray, size, distance, and amount. The rays are generated in a circular pattern around the center ray's direction.
     *
     * @param centerRay The central ray from which the beam is generated
     * @param size      The diameter of the circular area for the beam
     * @param distance  The distance from the center ray's origin to the target plane where the rays will intersect
     * @param amount    The number of rays to generate in the beam
     * @return A Beam object containing the generated rays
     */

    public Beam generateBeam(Ray centerRay, double size, double distance, int amount) {

        if (amount <= 1) {
            return new Beam(List.of(centerRay));
        }

        Vector vTo = centerRay.direction();

        double dotProd = vTo.dotProduct(Vector.AXIS_Z);

        Vector tempVector;
        if (Math.abs(dotProd) > 0.9) {
            tempVector = Vector.AXIS_Y;
        } else {
            tempVector = Vector.AXIS_Z;
        }

        Vector vRight = vTo.crossProduct(tempVector).normalize();
        Vector vUp = vRight.crossProduct(vTo).normalize();

        List<Point2D> samples = this.generateGrid(amount, size);
        List<Ray> rays = new ArrayList<>();

        Point pTarget = centerRay.origin().add(vTo.scale(distance));

        for (Point2D p2d : samples) {
            Point p = pTarget;

            if (p2d.getX() != 0) {
                p = p.add(vRight.scale(p2d.getX()));
            }
            if (p2d.getY() != 0) {
                p = p.add(vUp.scale(p2d.getY()));
            }

            rays.add(new Ray(centerRay.origin(), p.subtract(centerRay.origin())));
        }

        return new Beam(rays);
    }
}